/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinoAtivoRouteImport } from './routes/treino-ativo'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTreinoRouteImport } from './routes/_app.treino'
import { Route as AppSocialRouteImport } from './routes/_app.social'
import { Route as AppSaudeRouteImport } from './routes/_app.saude'
import { Route as AppRotasRouteImport } from './routes/_app.rotas'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppIacoachRouteImport } from './routes/_app.iacoach'
import { Route as AppHistoricoRouteImport } from './routes/_app.historico'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAtividadesRouteImport } from './routes/_app.atividades'

const TreinoAtivoRoute = TreinoAtivoRouteImport.update({
  id: '/treino-ativo',
  path: '/treino-ativo',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTreinoRoute = AppTreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AppSaudeRoute = AppSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AppRoute,
} as any)
const AppRotasRoute = AppRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppIacoachRoute = AppIacoachRouteImport.update({
  id: '/iacoach',
  path: '/iacoach',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAtividadesRoute = AppAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/treino-ativo': typeof TreinoAtivoRoute
  '/atividades': typeof AppAtividadesRoute
  '/dashboard': typeof AppDashboardRoute
  '/historico': typeof AppHistoricoRoute
  '/iacoach': typeof AppIacoachRoute
  '/perfil': typeof AppPerfilRoute
  '/rotas': typeof AppRotasRoute
  '/saude': typeof AppSaudeRoute
  '/social': typeof AppSocialRoute
  '/treino': typeof AppTreinoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/treino-ativo': typeof TreinoAtivoRoute
  '/atividades': typeof AppAtividadesRoute
  '/dashboard': typeof AppDashboardRoute
  '/historico': typeof AppHistoricoRoute
  '/iacoach': typeof AppIacoachRoute
  '/perfil': typeof AppPerfilRoute
  '/rotas': typeof AppRotasRoute
  '/saude': typeof AppSaudeRoute
  '/social': typeof AppSocialRoute
  '/treino': typeof AppTreinoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/treino-ativo': typeof TreinoAtivoRoute
  '/_app/atividades': typeof AppAtividadesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/iacoach': typeof AppIacoachRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/rotas': typeof AppRotasRoute
  '/_app/saude': typeof AppSaudeRoute
  '/_app/social': typeof AppSocialRoute
  '/_app/treino': typeof AppTreinoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/treino-ativo'
    | '/atividades'
    | '/dashboard'
    | '/historico'
    | '/iacoach'
    | '/perfil'
    | '/rotas'
    | '/saude'
    | '/social'
    | '/treino'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/treino-ativo'
    | '/atividades'
    | '/dashboard'
    | '/historico'
    | '/iacoach'
    | '/perfil'
    | '/rotas'
    | '/saude'
    | '/social'
    | '/treino'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/treino-ativo'
    | '/_app/atividades'
    | '/_app/dashboard'
    | '/_app/historico'
    | '/_app/iacoach'
    | '/_app/perfil'
    | '/_app/rotas'
    | '/_app/saude'
    | '/_app/social'
    | '/_app/treino'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  TreinoAtivoRoute: typeof TreinoAtivoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treino-ativo': {
      id: '/treino-ativo'
      path: '/treino-ativo'
      fullPath: '/treino-ativo'
      preLoaderRoute: typeof TreinoAtivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/treino': {
      id: '/_app/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof AppTreinoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/social': {
      id: '/_app/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saude': {
      id: '/_app/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof AppSaudeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rotas': {
      id: '/_app/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof AppRotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/iacoach': {
      id: '/_app/iacoach'
      path: '/iacoach'
      fullPath: '/iacoach'
      preLoaderRoute: typeof AppIacoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/atividades': {
      id: '/_app/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AppAtividadesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAtividadesRoute: typeof AppAtividadesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppIacoachRoute: typeof AppIacoachRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRotasRoute: typeof AppRotasRoute
  AppSaudeRoute: typeof AppSaudeRoute
  AppSocialRoute: typeof AppSocialRoute
  AppTreinoRoute: typeof AppTreinoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtividadesRoute: AppAtividadesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppIacoachRoute: AppIacoachRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRotasRoute: AppRotasRoute,
  AppSaudeRoute: AppSaudeRoute,
  AppSocialRoute: AppSocialRoute,
  AppTreinoRoute: AppTreinoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  TreinoAtivoRoute: TreinoAtivoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
